language: bash
env:
  global:
    - DOWNSTREAM_REPOSITORY=https://github.com/derhasi/packagist.git
    - DOWNSTREAM_BRANCH=packagist-webbundle
    - SUBTREE_PREFIX=src/Packagist/WebBundle
    - SUBTREE_BRANCH=master
branches:
  only:
    - script
before_script:
  - git config --global user.email "travisci@derhasi.de"
  - git config --global user.name "Travis CI"
script:
  - bash subtree-split.sh
