language: bash
env:
  global:
    - DOWNSTREAM_REPOSITORY=https://github.com/derhasi/packagist.git
    - DOWNSTREAM_BRANCH=packagist-webbundle
    - SUBTREE_PREFIX=src/Packagist/WebBundle
    - SUBTREE_BRANCH=master
    - secure: fcedh5AS1FqdTKnvNpHvIHXEL10GcMOT+UasqACHFd4tp04AAjH8XlfnqjuwrAh77timNHUkCDqARGPdxj7uY65z3xvDYOlYf+g1oUzR+A7CUZ12TmHJHDHX6ro+NJDYq4BRwRuXjDfE7hh2Ey9IB9pZNzuaVZlkEvdIergVMzM=
branches:
  only:
    - script
before_script:
  - git config --global user.email "travisci@derhasi.de"
  - git config --global user.name "Travis CI"
script:
  - bash subtree-split.sh
